### ISSUE TITLE
Does the plugin work with room based on sqlcipher?

### ISSUE THREAD

**Issue by yueban** [vkalmath/SqlCipherflipperPlugin#1]
Desktop os: mac os 10.15.4
Flipper desktop version: 0.37.0
Flipper android sdk version: 0.37.0
Cipherdatabase plugin version: 1.0.1

Problem Description:
I follow the steps on Readme, install the plugin and make sure the plugin is successfully installed cause it appears on Plugin Status panel with a green dot. But the database didn't show on the database panel in Flipper app. The database was created by room library with sqlcipher library.

here is the code to init database:
```java
final String cryptKey = "123456";
final byte[] passphrase = SQLiteDatabase.getBytes(cryptKey.toCharArray());
final SupportFactory factory = new SupportFactory(passphrase);
UserDatabase userDb = Room.databaseBuilder(context, UserDatabase.class, "user_db")
    .allowMainThreadQueries()
    .openHelperFactory(factory)
    .build();
```

**Comment by vkalmath** [comment]
did u install the android plugin for sqlcipher? it has its own counter part for android also..

**Comment by vkalmath** [comment]
This needs android plugin as well to work. It can be found here: https://github.com/vkalmath/flipper-sql-cipher-android/blob/master/README.md
Try it and let me know.
